import { Router } from "express";
import { deletePartoAborto, getPartoAborto, getPartosAbortos, postPartoAborto, putPartoAborto } from "../controllers/parto_aborto";
import validarJWT from "../helpers/validarJWT";
import validarCampos from "../middlewares/validar_campos";
const router = Router();
router.get('/', [validarJWT, validarCampos], getPartosAbortos);
router.get('/:par_id', [validarJWT, validarCampos], getPartoAborto);
router.post('/', [validarJWT, validarCampos], postPartoAborto);
router.put('/:par_id', [validarJWT, validarCampos], putPartoAborto);
router.delete('/:par:id', [validarJWT, validarCampos], deletePartoAborto);
export default router;